import React, { useMemo, useRef, useState } from "react";
import Card from "../../components/Card.jsx";
import Field from "../../components/Field.jsx";
import Button from "../../components/Button.jsx";
import { useStore } from "../../state/store.jsx";
import { requiredText } from "../../lib/validators.js";

export default function Chatbot() {
  const { state, dispatch, currentUser } = useStore();
  const user = currentUser();

  const messages = useMemo(
    () => state.chatbot_messages.filter((m) => m.user_id === user?.user_id),
    [state.chatbot_messages, user]
  );

  const [text, setText] = useState("");
  const [error, setError] = useState(null);
  const endRef = useRef(null);

  const send = () => {
    setError(null);
    const err = requiredText("Message", text);
    if (err) return setError(err);

    dispatch({ type: "chatbot/send", payload: { user_id: user.user_id, user_message: text.trim() } });
    setText("");
    setTimeout(() => endRef.current?.scrollIntoView({ behavior: "smooth" }), 0);
  };

  return (
    <div style={{ display: "grid", gap: 12 }}>
      <div className="row">
        <div>
          <h1 className="h1">AI Chatbot</h1>
          <div className="muted">Send text to the chatbot; responses are returned and stored (stubbed API).</div>
        </div>
        <div className="spacer" />
        <span className="badge">External AI API (stubbed)</span>
      </div>

      <Card title="Conversation" subtitle="Stored ChatbotMessages: user_message + ai_response">
        <div style={{ display: "grid", gap: 10, maxHeight: 420, overflow: "auto", paddingRight: 4 }}>
          {messages.length === 0 ? (
            <div className="muted">No messages yet.</div>
          ) : (
            messages.map((m) => (
              <div key={m.chatbot_message_id} style={{ display: "grid", gap: 6 }}>
                <div style={{ border: "1px solid var(--border)", borderRadius: 12, padding: 10 }}>
                  <div className="muted" style={{ fontSize: 12 }}>You</div>
                  <div>{m.user_message}</div>
                </div>
                <div style={{ border: "1px solid rgba(122,162,255,0.35)", borderRadius: 12, padding: 10, background: "rgba(122,162,255,0.08)" }}>
                  <div className="muted" style={{ fontSize: 12 }}>AI</div>
                  <div>{m.ai_response}</div>
                </div>
              </div>
            ))
          )}
          <div ref={endRef} />
        </div>

        <div className="hr" />

        <Field label="Message" error={error} hint="Prototype: stored locally (no networking)">
          <textarea className="textarea" value={text} onChange={(e) => setText(e.target.value)} />
        </Field>

        <div className="row">
          <Button onClick={send}>Send</Button>
          <div className="spacer" />
          <span className="muted" style={{ fontSize: 13 }}>Responses are generated by a stub function.</span>
        </div>
      </Card>
    </div>
  );
}
